title: "Kajian"

permalink: /:year/:month/:day/:title/

paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  
name: Zen
description: Developer
url: http://ngvuevueosas2018.github.io

timezone: Asia/Makassar